$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$biber = 'biber %O %B';
$bibtex_use = 2;
$clean_ext = 'aux bbl bcf blg fdb_latexmk fls log out run.xml toc lof lot';
